#!/bin/bash

set -euo pipefail

function eprintln() {
  >&2 echo "$1"
}

eprintln "Formatting sources"
cargo fmt -- --check

eprintln "Auditing dependencies"
cargo audit --deny warnings \
  --ignore RUSTSEC-2021-0127 # unmaintained serde_cbor

eprintln "Linting sources"
cargo clippy --all-targets -- -D warnings

# We cd to package directory as it's the only one with tests
# and cargo doesn't support feature flags in virtual workspaces
# https://github.com/rust-lang/cargo/issues/5364
pushd pretty_assertions

eprintln "Running tests (default)"
cargo test
eprintln "Running tests (alloc)"
cargo test --no-default-features --features alloc

eprintln "Running tests (nightly) (unstable)"
cargo +nightly test --features unstable
eprintln "Running tests (nightly) (alloc, unstable)"
cargo +nightly test --no-default-features --features alloc --features unstable

popd

eprintln "Running unit tests (unstable)"
cargo +nightly test --manifest-path pretty_assertions/Cargo.toml --all --features unstable

eprintln "Building documentation"
cargo doc --no-deps

eprintln "Running examples (standard)"
cargo run --example standard_assertion
eprintln "Running examples (pretty)"
cargo run --example pretty_assertion
