#!/bin/bash

set -exuo pipefail

rustup component add rustfmt clippy
cargo install cargo-audit
# For some reason cargo-tarpaulin doesn't like being cached on Github actions
# so always force installing it
cargo install cargo-tarpaulin --force
