#!/bin/bash

set -euxo pipefail

# Don't log the cargo login token while authenticating
set +x
echo "cargo login ***********************************"
cargo login "${CARGO_LOGIN_TOKEN}"
set -x

cargo publish
